DROP TABLE IF EXISTS poc_product;

CREATE TABLE IF NOT EXISTS poc_product (
  product_id VARCHAR(255) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL,
  deleted BOOLEAN NOT NULL,
  CREATED_TMST TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_TMST TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(product_id)
);

DROP TABLE IF EXISTS poc_business_unit;

CREATE TABLE IF NOT EXISTS poc_business_unit (
  business_unit_id VARCHAR(255) NOT NULL,
  business_unit_name VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL,
  deleted BOOLEAN NOT NULL,
  CREATED_TMST TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_TMST TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(business_unit_id)
);